# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b64e83b16eb6164c384c03e0f49b6a48accd7ed9b95b58848e677510f0f92b177dee765853643a68df77a924219c6b85a3ae797d8871e0610a4c9d44bfba765c

test:
  secret_key_base: 8c8c8542732b0af161bf9737460b7c5070f9723ff4c72955f6907f015cea35035afc0b914118df8affc0d501dd71f903c0242ded3f8afd52245bd218fdc947bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
